import { useCallback, useEffect, useMemo, useState } from "react";
import { Code2, File, Files, Folder, FolderOpen, LoaderCircle, RefreshCw, Search, Sparkles, X } from "lucide-react";
import type { RuntimeSnapshot, WorkspaceFile, WorkspaceTreeEntry } from "../shared/contracts";
import { rpc } from "./bridge";

type Mode = "files" | "search" | "code" | "skills" | "work";
type Props = { snapshot: RuntimeSnapshot; onClose: () => void; onJump: (id: string) => void };
const modes: Array<{ id: Mode; label: string; icon: typeof Files }> = [
  { id: "files", label: "Files", icon: Files }, { id: "search", label: "Search", icon: Search },
  { id: "code", label: "Code", icon: Code2 }, { id: "skills", label: "Skills", icon: Sparkles },
];
function flatten(entries: WorkspaceTreeEntry[]): WorkspaceTreeEntry[] { return entries.flatMap((entry) => [entry, ...(entry.children ? flatten(entry.children) : [])]); }
function formatBytes(size?: number) { if (size === undefined) return ""; if (size < 1_000) return `${size} B`; if (size < 1_000_000) return `${(size / 1_000).toFixed(1)} KB`; return `${(size / 1_000_000).toFixed(1)} MB`; }

export function WorkspacePane({ snapshot, onClose, onJump }: Props) {
  const [mode, setMode] = useState<Mode>("files"); const [tree, setTree] = useState<WorkspaceTreeEntry[]>([]);
  const [selectedPath, setSelectedPath] = useState<string | null>(null); const [file, setFile] = useState<WorkspaceFile | null>(null);
  const [draft, setDraft] = useState(""); const [query, setQuery] = useState(""); const [searchMode, setSearchMode] = useState<"bm25" | "vector" | "hybrid">("bm25");
  const [results, setResults] = useState<Array<{ id: string; content: string; score: number }>>([]); const [skills, setSkills] = useState<Array<{ name: string; description: string; path: string; source: string; conflict: boolean; content?: string }>>([]);
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [dirty, setDirty] = useState(false);
  const scopeKey = `${snapshot.activeThreadId}:${snapshot.activeWorkspace.label}`;
  const refresh = useCallback(async () => { setBusy(true); setError(null); try { setTree(await rpc.request["workspace.tree"]({ path: "", depth: 4 })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Workspace is unavailable"); } finally { setBusy(false); } }, []);
  useEffect(() => { setTree([]); setSelectedPath(null); setFile(null); setResults([]); setError(null); if (snapshot.activeWorkspace.availability === "ready") void refresh(); }, [scopeKey, snapshot.activeWorkspace.availability, refresh]);
  const openFile = async (path: string) => { setBusy(true); setError(null); try { const next = await rpc.request["workspace.read"]({ path }); setSelectedPath(path); setFile(next); setDraft(next.content ?? ""); setDirty(false); } catch (reason) { setError(reason instanceof Error ? reason.message : "File could not be opened"); } finally { setBusy(false); } };
  const save = async () => { if (!file || file.kind !== "text") return; setBusy(true); try { const next = await rpc.request["workspace.write"]({ path: file.path, content: draft, expectedVersion: file.version }); setFile(next); setDirty(false); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "File could not be saved"); } finally { setBusy(false); } };
  const search = async () => { if (!query.trim()) return; setBusy(true); setError(null); try { setResults(await rpc.request["workspace.search"]({ query: query.trim(), mode: searchMode, topK: 20 })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Search failed"); } finally { setBusy(false); } };
  const loadSkills = async () => { setBusy(true); try { setSkills(await rpc.request["workspace.skills"]({ load: true })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Skills could not be loaded"); } finally { setBusy(false); } };
  useEffect(() => { if (mode === "skills" && skills.length === 0) void loadSkills(); }, [mode]);
  const files = useMemo(() => flatten(tree).filter((item) => item.kind === "file"), [tree]);
  return <aside className="workspace-pane" id="workspace-pane" aria-label="Workspace">
    <header className="workspace-pane__head"><div><span className="caption-uppercase">Workspace</span><strong>{snapshot.activeWorkspace.label}</strong></div><button type="button" className="icon-btn" onClick={onClose} aria-label="Close workspace"><X size={17} /></button></header>
    <nav className="workspace-pane__tabs" aria-label="Workspace views">{modes.map(({ id, label, icon: Glyph }) => <button key={id} type="button" className={mode === id ? "active" : ""} onClick={() => setMode(id)} aria-current={mode === id ? "page" : undefined}><Glyph size={15} /><span>{label}</span></button>)}</nav>
    {busy && <div className="workspace-pane__loading"><LoaderCircle size={15} className="spin" /> Working…</div>}{error && <p className="workspace-pane__error" role="alert">{error}</p>}
    <div className="workspace-pane__body">
      {mode === "files" && <>{file ? <section className="file-preview"><div className="file-preview__bar"><button type="button" onClick={() => { setFile(null); setSelectedPath(null); }}>← Files</button><span title={file.path}>{file.path}</span>{file.kind === "text" && <button type="button" disabled={!dirty || busy} onClick={() => void save()}>Save</button>}</div>{file.kind === "text" ? <textarea aria-label={`Edit ${file.path}`} value={draft} onChange={(event) => { setDraft(event.target.value); setDirty(event.target.value !== file.content); }} spellCheck={false} /> : file.kind === "image" ? <img src={file.dataUrl} alt={file.path} /> : file.kind === "pdf" ? <iframe src={file.dataUrl} title={file.path} /> : <div className="workspace-empty">Binary preview is unavailable.</div>}<footer>{formatBytes(file.size)} · {new Date(file.modifiedAt).toLocaleString()}{file.truncated ? " · Preview truncated" : ""}</footer></section> : <section className="file-browser"><div className="workspace-toolbar"><span>{files.length} files</span><button type="button" onClick={() => void refresh()}><RefreshCw size={14} /> Refresh</button></div>{tree.length === 0 && !busy ? <div className="workspace-empty"><FolderOpen size={26} /><p>This workspace has no visible files.</p></div> : <Tree entries={tree} selected={selectedPath} onOpen={(path) => void openFile(path)} />}</section>}</>}
      {mode === "search" && <section className="workspace-search"><form onSubmit={(event) => { event.preventDefault(); void search(); }}><div className="workspace-search__input"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search indexed workspace" aria-label="Search workspace" /><button type="submit">Search</button></div><div className="workspace-search__modes">{(["bm25", "vector", "hybrid"] as const).map((item) => <button type="button" className={searchMode === item ? "active" : ""} onClick={() => setSearchMode(item)} key={item}>{item === "bm25" ? "Keyword" : item === "vector" ? "Semantic" : "Hybrid"}</button>)}</div></form>{results.length === 0 ? <div className="workspace-empty"><Search size={26} /><p>Index files, then search by keyword or meaning.</p><button type="button" disabled={!files.length} onClick={() => void rpc.request["workspace.index"]({ paths: files.map((item) => item.path) })}>Index {files.length} files</button></div> : <ul className="search-results">{results.map((result) => <li key={result.id}><button type="button" onClick={() => void openFile(result.id)}><strong>{result.id}</strong><span>{Math.round(result.score * 100)}%</span><p>{result.content.slice(0, 240)}</p></button></li>)}</ul>}</section>}
      {mode === "code" && <section className="workspace-empty"><Code2 size={28} /><h3>Semantic inspection</h3><p>Open a TypeScript or JavaScript file, then ask Proteus to inspect a symbol. Mastra LSP results stay rooted in this workspace.</p>{file?.path && <button type="button" onClick={() => setMode("files")}>Return to {file.path}</button>}</section>}
      {mode === "skills" && <section>{skills.length === 0 && !busy ? <div className="workspace-empty"><Sparkles size={28} /><p>No project skills were discovered.</p></div> : <ul className="skill-list">{skills.map((skill) => <li key={`${skill.source}:${skill.name}`}><details><summary><span><strong>{skill.name}</strong><small>{skill.description}</small></span>{skill.conflict && <b>Conflict</b>}</summary><code>{skill.path}</code><pre>{skill.content}</pre></details></li>)}</ul>}</section>}
      {mode === "work" && <section>{snapshot.workbench.pendingInteractions.map((item) => <button key={item.id} type="button" onClick={() => onJump(item.id)}>{item.title}</button>)}</section>}
    </div>
  </aside>;
}
function Tree({ entries, selected, onOpen }: { entries: WorkspaceTreeEntry[]; selected: string | null; onOpen: (path: string) => void }) { return <ul className="workspace-tree">{entries.map((entry) => <li key={entry.path}>{entry.kind === "directory" ? <details open><summary><Folder size={14} />{entry.name}</summary>{entry.children && <Tree entries={entry.children} selected={selected} onOpen={onOpen} />}</details> : <button type="button" className={selected === entry.path ? "selected" : ""} onClick={() => onOpen(entry.path)}><File size={14} /><span>{entry.name}</span><small>{formatBytes(entry.size)}</small></button>}</li>)}</ul>; }
