/** Tools available after native submit_plan approval. */
export const APPROVED_PLAN_TOOLS = [
  "ask_user",
  "read_plan",
  "task_write",
  "task_update",
  "task_complete",
  "task_check",
  "mastra_workspace_read_file",
  "mastra_workspace_list_files",
  "mastra_workspace_file_stat",
  "mastra_workspace_grep",
  "mastra_workspace_write_file",
  "mastra_workspace_edit_file",
  "mastra_workspace_mkdir",
  "mastra_workspace_delete",
  "mastra_workspace_execute_command",
  "mastra_workspace_get_process_output",
  "mastra_workspace_kill_process",
] as const;
